version: "2"
services:
  app:
    container_name: phonecase-pm2-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./dist/data/db
    ports:
      - "27017:27017"